---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: chart-of-charts
spec:
  releaseName: chart-of-charts
  chart:
    git: git@github.com:kodachimaru/gitops-demo-helm-operator.git
    path: chart-of-charts
    ref: master
